비지도학습 1

In [3]:
from sklearn.ensemble import IsolationForest
import numpy as np
import pandas as pd

In [12]:
# 미션용 가상 센서 데이터 생성 (정상 상태 300개 + 오작동 상태 25개 합성)
rng = np.random.RandomState(100)
X_sensor_normal = 0.5 * rng.randn(300, 5)
X_sensor_faulty = rng.uniform(low=-5, high=5, size=(25, 5))
X_sensor = np.vstack([X_sensor_normal, X_sensor_faulty])

print(X_sensor)
sensor_df = pd.DataFrame(X_sensor)

[[-0.87488274  0.1713402   0.5765179  -0.12621802  0.49066039]
 [ 0.25710942  0.11058983 -0.53502167 -0.09474792  0.12750072]
 [-0.22901349  0.21758174 -0.29179753  0.40842354  0.3363604 ]
 ...
 [ 0.52390679  1.04059191 -0.1426875  -2.67099151 -4.22126872]
 [ 4.24318884 -4.09325689 -0.50165466 -1.06080764  4.24531439]
 [ 0.63005795 -2.17999994  0.42842026 -1.01240121  0.47817628]]


In [13]:
sensor_df

,0,1,2,3,4
0,-0.874883,0.171340,0.576518,-0.126218,0.490660
1,0.257109,0.110590,-0.535022,-0.094748,0.127501
2,-0.229013,0.217582,-0.291798,0.408424,0.336360
3,-0.052206,-0.265640,0.514866,-0.219068,-0.559159
4,0.809491,0.770803,-0.125940,-0.421218,0.092259
...,...,...,...,...,...
320,-2.599938,3.245204,-2.163900,-1.370174,-2.308651
321,-4.739155,0.180305,-0.805694,2.508764,-2.989993
322,0.523907,1.040592,-0.142687,-2.670992,-4.221269
323,4.243189,-4.093257,-0.501655,-1.060808,4.245314


In [14]:
# 모델 생성
model = IsolationForest(
    n_estimators=100,
    contamination=0.08,
    random_state=42
)

In [15]:
outlier_preds = model.fit_predict(sensor_df)

In [17]:
outlier_preds

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1

In [ ]:
# numpy의 sum을 통해 이상치의 개수 계산
anomaly_count = np.sum(outlier_preds == -1)
print(f'이상치 샘플의 개수 : {anomaly_count}개')

이상치 샘플의 개수 : 26개
